// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

package mage.client.record;

public final class RecordProtos {
  private RecordProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:record.Match)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string deck_type = 2;</code>
     */
    boolean hasDeckType();
    /**
     * <code>optional string deck_type = 2;</code>
     */
    java.lang.String getDeckType();
    /**
     * <code>optional string deck_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeckTypeBytes();

    /**
     * <code>optional string players = 3;</code>
     */
    boolean hasPlayers();
    /**
     * <code>optional string players = 3;</code>
     */
    java.lang.String getPlayers();
    /**
     * <code>optional string players = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlayersBytes();

    /**
     * <code>optional string game_type = 4;</code>
     */
    boolean hasGameType();
    /**
     * <code>optional string game_type = 4;</code>
     */
    java.lang.String getGameType();
    /**
     * <code>optional string game_type = 4;</code>
     */
    com.google.protobuf.ByteString
        getGameTypeBytes();

    /**
     * <code>optional string result = 5;</code>
     */
    boolean hasResult();
    /**
     * <code>optional string result = 5;</code>
     */
    java.lang.String getResult();
    /**
     * <code>optional string result = 5;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    /**
     * <code>optional int64 start_time_msec = 6;</code>
     */
    boolean hasStartTimeMsec();
    /**
     * <code>optional int64 start_time_msec = 6;</code>
     */
    long getStartTimeMsec();

    /**
     * <code>optional int64 end_time_msec = 7;</code>
     */
    boolean hasEndTimeMsec();
    /**
     * <code>optional int64 end_time_msec = 7;</code>
     */
    long getEndTimeMsec();
  }
  /**
   * Protobuf type {@code record.Match}
   */
  public  static final class Match extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:record.Match)
      MatchOrBuilder {
    // Use Match.newBuilder() to construct.
    private Match(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Match() {
      id_ = 0;
      deckType_ = "";
      players_ = "";
      gameType_ = "";
      result_ = "";
      startTimeMsec_ = 0L;
      endTimeMsec_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Match(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deckType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              players_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              gameType_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              result_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              startTimeMsec_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              endTimeMsec_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mage.client.record.RecordProtos.internal_static_record_Match_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mage.client.record.RecordProtos.internal_static_record_Match_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mage.client.record.RecordProtos.Match.class, mage.client.record.RecordProtos.Match.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DECK_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object deckType_;
    /**
     * <code>optional string deck_type = 2;</code>
     */
    public boolean hasDeckType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string deck_type = 2;</code>
     */
    public java.lang.String getDeckType() {
      java.lang.Object ref = deckType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deckType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deck_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeckTypeBytes() {
      java.lang.Object ref = deckType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deckType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERS_FIELD_NUMBER = 3;
    private volatile java.lang.Object players_;
    /**
     * <code>optional string players = 3;</code>
     */
    public boolean hasPlayers() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string players = 3;</code>
     */
    public java.lang.String getPlayers() {
      java.lang.Object ref = players_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          players_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string players = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlayersBytes() {
      java.lang.Object ref = players_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        players_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAME_TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object gameType_;
    /**
     * <code>optional string game_type = 4;</code>
     */
    public boolean hasGameType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string game_type = 4;</code>
     */
    public java.lang.String getGameType() {
      java.lang.Object ref = gameType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string game_type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGameTypeBytes() {
      java.lang.Object ref = gameType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 5;
    private volatile java.lang.Object result_;
    /**
     * <code>optional string result = 5;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string result = 5;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string result = 5;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_MSEC_FIELD_NUMBER = 6;
    private long startTimeMsec_;
    /**
     * <code>optional int64 start_time_msec = 6;</code>
     */
    public boolean hasStartTimeMsec() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 start_time_msec = 6;</code>
     */
    public long getStartTimeMsec() {
      return startTimeMsec_;
    }

    public static final int END_TIME_MSEC_FIELD_NUMBER = 7;
    private long endTimeMsec_;
    /**
     * <code>optional int64 end_time_msec = 7;</code>
     */
    public boolean hasEndTimeMsec() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 end_time_msec = 7;</code>
     */
    public long getEndTimeMsec() {
      return endTimeMsec_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deckType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, players_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, gameType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, result_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, startTimeMsec_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, endTimeMsec_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deckType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, players_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, gameType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, result_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, startTimeMsec_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, endTimeMsec_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static mage.client.record.RecordProtos.Match parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Match parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mage.client.record.RecordProtos.Match parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mage.client.record.RecordProtos.Match parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mage.client.record.RecordProtos.Match prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code record.Match}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:record.Match)
        mage.client.record.RecordProtos.MatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mage.client.record.RecordProtos.internal_static_record_Match_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mage.client.record.RecordProtos.internal_static_record_Match_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mage.client.record.RecordProtos.Match.class, mage.client.record.RecordProtos.Match.Builder.class);
      }

      // Construct using mage.client.record.RecordProtos.Match.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        deckType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        players_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        gameType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        startTimeMsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        endTimeMsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mage.client.record.RecordProtos.internal_static_record_Match_descriptor;
      }

      public mage.client.record.RecordProtos.Match getDefaultInstanceForType() {
        return mage.client.record.RecordProtos.Match.getDefaultInstance();
      }

      public mage.client.record.RecordProtos.Match build() {
        mage.client.record.RecordProtos.Match result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mage.client.record.RecordProtos.Match buildPartial() {
        mage.client.record.RecordProtos.Match result = new mage.client.record.RecordProtos.Match(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deckType_ = deckType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.players_ = players_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.gameType_ = gameType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.startTimeMsec_ = startTimeMsec_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.endTimeMsec_ = endTimeMsec_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mage.client.record.RecordProtos.Match) {
          return mergeFrom((mage.client.record.RecordProtos.Match)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mage.client.record.RecordProtos.Match other) {
        if (other == mage.client.record.RecordProtos.Match.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDeckType()) {
          bitField0_ |= 0x00000002;
          deckType_ = other.deckType_;
          onChanged();
        }
        if (other.hasPlayers()) {
          bitField0_ |= 0x00000004;
          players_ = other.players_;
          onChanged();
        }
        if (other.hasGameType()) {
          bitField0_ |= 0x00000008;
          gameType_ = other.gameType_;
          onChanged();
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000010;
          result_ = other.result_;
          onChanged();
        }
        if (other.hasStartTimeMsec()) {
          setStartTimeMsec(other.getStartTimeMsec());
        }
        if (other.hasEndTimeMsec()) {
          setEndTimeMsec(other.getEndTimeMsec());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mage.client.record.RecordProtos.Match parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mage.client.record.RecordProtos.Match) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object deckType_ = "";
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public boolean hasDeckType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public java.lang.String getDeckType() {
        java.lang.Object ref = deckType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deckType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeckTypeBytes() {
        java.lang.Object ref = deckType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deckType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public Builder setDeckType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deckType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public Builder clearDeckType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deckType_ = getDefaultInstance().getDeckType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deck_type = 2;</code>
       */
      public Builder setDeckTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deckType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object players_ = "";
      /**
       * <code>optional string players = 3;</code>
       */
      public boolean hasPlayers() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string players = 3;</code>
       */
      public java.lang.String getPlayers() {
        java.lang.Object ref = players_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            players_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string players = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlayersBytes() {
        java.lang.Object ref = players_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          players_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string players = 3;</code>
       */
      public Builder setPlayers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        players_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string players = 3;</code>
       */
      public Builder clearPlayers() {
        bitField0_ = (bitField0_ & ~0x00000004);
        players_ = getDefaultInstance().getPlayers();
        onChanged();
        return this;
      }
      /**
       * <code>optional string players = 3;</code>
       */
      public Builder setPlayersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        players_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gameType_ = "";
      /**
       * <code>optional string game_type = 4;</code>
       */
      public boolean hasGameType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string game_type = 4;</code>
       */
      public java.lang.String getGameType() {
        java.lang.Object ref = gameType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gameType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string game_type = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGameTypeBytes() {
        java.lang.Object ref = gameType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string game_type = 4;</code>
       */
      public Builder setGameType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string game_type = 4;</code>
       */
      public Builder clearGameType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gameType_ = getDefaultInstance().getGameType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string game_type = 4;</code>
       */
      public Builder setGameTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        gameType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>optional string result = 5;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string result = 5;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            result_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string result = 5;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string result = 5;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 5;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000010);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>optional string result = 5;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        result_ = value;
        onChanged();
        return this;
      }

      private long startTimeMsec_ ;
      /**
       * <code>optional int64 start_time_msec = 6;</code>
       */
      public boolean hasStartTimeMsec() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 start_time_msec = 6;</code>
       */
      public long getStartTimeMsec() {
        return startTimeMsec_;
      }
      /**
       * <code>optional int64 start_time_msec = 6;</code>
       */
      public Builder setStartTimeMsec(long value) {
        bitField0_ |= 0x00000020;
        startTimeMsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 start_time_msec = 6;</code>
       */
      public Builder clearStartTimeMsec() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startTimeMsec_ = 0L;
        onChanged();
        return this;
      }

      private long endTimeMsec_ ;
      /**
       * <code>optional int64 end_time_msec = 7;</code>
       */
      public boolean hasEndTimeMsec() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 end_time_msec = 7;</code>
       */
      public long getEndTimeMsec() {
        return endTimeMsec_;
      }
      /**
       * <code>optional int64 end_time_msec = 7;</code>
       */
      public Builder setEndTimeMsec(long value) {
        bitField0_ |= 0x00000040;
        endTimeMsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 end_time_msec = 7;</code>
       */
      public Builder clearEndTimeMsec() {
        bitField0_ = (bitField0_ & ~0x00000040);
        endTimeMsec_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:record.Match)
    }

    // @@protoc_insertion_point(class_scope:record.Match)
    private static final mage.client.record.RecordProtos.Match DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mage.client.record.RecordProtos.Match();
    }

    public static mage.client.record.RecordProtos.Match getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Match>
        PARSER = new com.google.protobuf.AbstractParser<Match>() {
      public Match parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Match(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Match> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Match> getParserForType() {
      return PARSER;
    }

    public mage.client.record.RecordProtos.Match getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatchesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:record.Matches)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    java.util.List<mage.client.record.RecordProtos.Match> 
        getMatchesList();
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    mage.client.record.RecordProtos.Match getMatches(int index);
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    int getMatchesCount();
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    java.util.List<? extends mage.client.record.RecordProtos.MatchOrBuilder> 
        getMatchesOrBuilderList();
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    mage.client.record.RecordProtos.MatchOrBuilder getMatchesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code record.Matches}
   */
  public  static final class Matches extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:record.Matches)
      MatchesOrBuilder {
    // Use Matches.newBuilder() to construct.
    private Matches(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Matches() {
      matches_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Matches(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                matches_ = new java.util.ArrayList<mage.client.record.RecordProtos.Match>();
                mutable_bitField0_ |= 0x00000001;
              }
              matches_.add(input.readMessage(mage.client.record.RecordProtos.Match.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          matches_ = java.util.Collections.unmodifiableList(matches_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mage.client.record.RecordProtos.internal_static_record_Matches_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mage.client.record.RecordProtos.internal_static_record_Matches_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mage.client.record.RecordProtos.Matches.class, mage.client.record.RecordProtos.Matches.Builder.class);
    }

    public static final int MATCHES_FIELD_NUMBER = 1;
    private java.util.List<mage.client.record.RecordProtos.Match> matches_;
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    public java.util.List<mage.client.record.RecordProtos.Match> getMatchesList() {
      return matches_;
    }
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    public java.util.List<? extends mage.client.record.RecordProtos.MatchOrBuilder> 
        getMatchesOrBuilderList() {
      return matches_;
    }
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    public int getMatchesCount() {
      return matches_.size();
    }
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    public mage.client.record.RecordProtos.Match getMatches(int index) {
      return matches_.get(index);
    }
    /**
     * <code>repeated .record.Match matches = 1;</code>
     */
    public mage.client.record.RecordProtos.MatchOrBuilder getMatchesOrBuilder(
        int index) {
      return matches_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < matches_.size(); i++) {
        output.writeMessage(1, matches_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < matches_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, matches_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static mage.client.record.RecordProtos.Matches parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Matches parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static mage.client.record.RecordProtos.Matches parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static mage.client.record.RecordProtos.Matches parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mage.client.record.RecordProtos.Matches prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code record.Matches}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:record.Matches)
        mage.client.record.RecordProtos.MatchesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mage.client.record.RecordProtos.internal_static_record_Matches_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mage.client.record.RecordProtos.internal_static_record_Matches_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mage.client.record.RecordProtos.Matches.class, mage.client.record.RecordProtos.Matches.Builder.class);
      }

      // Construct using mage.client.record.RecordProtos.Matches.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMatchesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mage.client.record.RecordProtos.internal_static_record_Matches_descriptor;
      }

      public mage.client.record.RecordProtos.Matches getDefaultInstanceForType() {
        return mage.client.record.RecordProtos.Matches.getDefaultInstance();
      }

      public mage.client.record.RecordProtos.Matches build() {
        mage.client.record.RecordProtos.Matches result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mage.client.record.RecordProtos.Matches buildPartial() {
        mage.client.record.RecordProtos.Matches result = new mage.client.record.RecordProtos.Matches(this);
        int from_bitField0_ = bitField0_;
        if (matchesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            matches_ = java.util.Collections.unmodifiableList(matches_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.matches_ = matches_;
        } else {
          result.matches_ = matchesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mage.client.record.RecordProtos.Matches) {
          return mergeFrom((mage.client.record.RecordProtos.Matches)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mage.client.record.RecordProtos.Matches other) {
        if (other == mage.client.record.RecordProtos.Matches.getDefaultInstance()) return this;
        if (matchesBuilder_ == null) {
          if (!other.matches_.isEmpty()) {
            if (matches_.isEmpty()) {
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMatchesIsMutable();
              matches_.addAll(other.matches_);
            }
            onChanged();
          }
        } else {
          if (!other.matches_.isEmpty()) {
            if (matchesBuilder_.isEmpty()) {
              matchesBuilder_.dispose();
              matchesBuilder_ = null;
              matches_ = other.matches_;
              bitField0_ = (bitField0_ & ~0x00000001);
              matchesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMatchesFieldBuilder() : null;
            } else {
              matchesBuilder_.addAllMessages(other.matches_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mage.client.record.RecordProtos.Matches parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mage.client.record.RecordProtos.Matches) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<mage.client.record.RecordProtos.Match> matches_ =
        java.util.Collections.emptyList();
      private void ensureMatchesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          matches_ = new java.util.ArrayList<mage.client.record.RecordProtos.Match>(matches_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          mage.client.record.RecordProtos.Match, mage.client.record.RecordProtos.Match.Builder, mage.client.record.RecordProtos.MatchOrBuilder> matchesBuilder_;

      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public java.util.List<mage.client.record.RecordProtos.Match> getMatchesList() {
        if (matchesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(matches_);
        } else {
          return matchesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public int getMatchesCount() {
        if (matchesBuilder_ == null) {
          return matches_.size();
        } else {
          return matchesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public mage.client.record.RecordProtos.Match getMatches(int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);
        } else {
          return matchesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder setMatches(
          int index, mage.client.record.RecordProtos.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.set(index, value);
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder setMatches(
          int index, mage.client.record.RecordProtos.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.set(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder addMatches(mage.client.record.RecordProtos.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder addMatches(
          int index, mage.client.record.RecordProtos.Match value) {
        if (matchesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMatchesIsMutable();
          matches_.add(index, value);
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder addMatches(
          mage.client.record.RecordProtos.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder addMatches(
          int index, mage.client.record.RecordProtos.Match.Builder builderForValue) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.add(index, builderForValue.build());
          onChanged();
        } else {
          matchesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder addAllMatches(
          java.lang.Iterable<? extends mage.client.record.RecordProtos.Match> values) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, matches_);
          onChanged();
        } else {
          matchesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder clearMatches() {
        if (matchesBuilder_ == null) {
          matches_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          matchesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public Builder removeMatches(int index) {
        if (matchesBuilder_ == null) {
          ensureMatchesIsMutable();
          matches_.remove(index);
          onChanged();
        } else {
          matchesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public mage.client.record.RecordProtos.Match.Builder getMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public mage.client.record.RecordProtos.MatchOrBuilder getMatchesOrBuilder(
          int index) {
        if (matchesBuilder_ == null) {
          return matches_.get(index);  } else {
          return matchesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public java.util.List<? extends mage.client.record.RecordProtos.MatchOrBuilder> 
           getMatchesOrBuilderList() {
        if (matchesBuilder_ != null) {
          return matchesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(matches_);
        }
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public mage.client.record.RecordProtos.Match.Builder addMatchesBuilder() {
        return getMatchesFieldBuilder().addBuilder(
            mage.client.record.RecordProtos.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public mage.client.record.RecordProtos.Match.Builder addMatchesBuilder(
          int index) {
        return getMatchesFieldBuilder().addBuilder(
            index, mage.client.record.RecordProtos.Match.getDefaultInstance());
      }
      /**
       * <code>repeated .record.Match matches = 1;</code>
       */
      public java.util.List<mage.client.record.RecordProtos.Match.Builder> 
           getMatchesBuilderList() {
        return getMatchesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          mage.client.record.RecordProtos.Match, mage.client.record.RecordProtos.Match.Builder, mage.client.record.RecordProtos.MatchOrBuilder> 
          getMatchesFieldBuilder() {
        if (matchesBuilder_ == null) {
          matchesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              mage.client.record.RecordProtos.Match, mage.client.record.RecordProtos.Match.Builder, mage.client.record.RecordProtos.MatchOrBuilder>(
                  matches_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          matches_ = null;
        }
        return matchesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:record.Matches)
    }

    // @@protoc_insertion_point(class_scope:record.Matches)
    private static final mage.client.record.RecordProtos.Matches DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mage.client.record.RecordProtos.Matches();
    }

    public static mage.client.record.RecordProtos.Matches getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Matches>
        PARSER = new com.google.protobuf.AbstractParser<Matches>() {
      public Matches parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Matches(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Matches> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Matches> getParserForType() {
      return PARSER;
    }

    public mage.client.record.RecordProtos.Matches getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_record_Match_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_record_Match_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_record_Matches_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_record_Matches_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014record.proto\022\006record\"\212\001\n\005Match\022\n\n\002id\030\001" +
      " \001(\005\022\021\n\tdeck_type\030\002 \001(\t\022\017\n\007players\030\003 \001(\t" +
      "\022\021\n\tgame_type\030\004 \001(\t\022\016\n\006result\030\005 \001(\t\022\027\n\017s" +
      "tart_time_msec\030\006 \001(\003\022\025\n\rend_time_msec\030\007 " +
      "\001(\003\")\n\007Matches\022\036\n\007matches\030\001 \003(\0132\r.record" +
      ".MatchB\"\n\022mage.client.recordB\014RecordProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_record_Match_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_record_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_record_Match_descriptor,
        new java.lang.String[] { "Id", "DeckType", "Players", "GameType", "Result", "StartTimeMsec", "EndTimeMsec", });
    internal_static_record_Matches_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_record_Matches_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_record_Matches_descriptor,
        new java.lang.String[] { "Matches", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
